controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    slatol_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

slatol_position_controller:
  ros__parameters:
    joints:
      - hip_haa_joint
      - hip_hfe_joint
      - knee_kfe_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity