controller_manager:
  ros__parameters:
    update_rate: 100

    slatol_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

slatol_position_controller:
  ros__parameters:
    joints:
      - hip_haa_joint
      - hip_hfe_joint
      - knee_kfe_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    
    gains:
      hip_haa_joint: {p: 1000.0, i: 0.0, d: 30.0}
      hip_hfe_joint: {p: 2000.0, i: 0.0, d: 50.0}
      knee_kfe_joint: {p: 2000.0, i: 0.0, d: 50.0}